### ISSUE TITLE
Error when using with gulp-less

### ISSUE THREAD

**Issue by LukeMauldin** [murphydanger/gulp-minify-css#109]
I get this error when using with the less plugin:
```
[18:26:42] Using gulpfile /var/www/html/pmtool/erp-extender/pms420/gulpfile.js
[18:26:42] Starting 'styles'...
/var/www/html/pmtool/erp-extender/pms420/node_modules/gulp-less/node_modules/less/lib/less/plugin-manager.js:29
    plugin.install(this.less, this);
           ^
TypeError: undefined is not a function
    at PluginManager.addPlugin (/var/www/html/pmtool/erp-extender/pms420/node_modules/gulp-less/node_modules/less/lib/less/plugin-manager.js:29:12)
    at PluginManager.addPlugins (/var/www/html/pmtool/erp-extender/pms420/node_modules/gulp-less/node_modules/less/lib/less/plugin-manager.js:19:18)
    at Object.parse (/var/www/html/pmtool/erp-extender/pms420/node_modules/gulp-less/node_modules/less/lib/less/parse.js:34:27)
    at Object.render (/var/www/html/pmtool/erp-extender/pms420/node_modules/gulp-less/node_modules/less/lib/less/render.js:25:18)
    at Less._render (/var/www/html/pmtool/erp-extender/pms420/node_modules/gulp-less/node_modules/accord/lib/adapters/less.js:39:19)
    at Less.Adapter.render (/var/www/html/pmtool/erp-extender/pms420/node_modules/gulp-less/node_modules/accord/lib/adapter_base.js:122:19)
    at DestroyableTransform._transform (/var/www/html/pmtool/erp-extender/pms420/node_modules/gulp-less/index.js:38:10)
    at DestroyableTransform.Transform._read (/var/www/html/pmtool/erp-extender/pms420/node_modules/gulp-less/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:184:10)
    at DestroyableTransform.Transform._write (/var/www/html/pmtool/erp-extender/pms420/node_modules/gulp-less/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:172:12)
    at doWrite (/var/www/html/pmtool/erp-extender/pms420/node_modules/gulp-less/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:237:10)
```

gulpfile
```
var gulp = require('gulp');
var changed = require('gulp-changed');
var imagemin = require('gulp-imagemin');
var include = require('gulp-include');
var uglify = require('gulp-uglify');
var rename = require('gulp-rename');
var filter = require('gulp-filter');
var less = require('gulp-less');
var path = require('path');
var minifyCss = require('gulp-minify-css');
var sourcemaps = require('gulp-sourcemaps');
var del = require('del');

gulp.task("styles", function() {
    var minify = minifyCss({ advanced: true });
    return gulp.src(['./assets/styles/application.less', './assets/styles/*/*.less'])
        .pipe(sourcemaps.init())
        .pipe(less({
            plugins: [minify]
        }))
        .pipe(sourcemaps.write('.'))
        .pipe(gulp.dest('./webroot/styles'));
});
```

**Comment by LukeMauldin** [comment]
Nevermind, I should have used a pipe() instead of a plugin command.

**Comment by jasonszhao** [comment]
Same thing happens to me when I pass in the `plugins` property. Why?

**Comment by shinnn** [comment]
:point_right: https://github.com/plus3network/gulp-less/issues
