### ISSUE TITLE
Error with clean-css 3.4.2

### ISSUE THREAD

**Issue by g----** [murphydanger/gulp-minify-css#120]
New version for `clean-css` breaks build.

Could you please:
+ fix version in `package.json` (remove `^` for every dependency to avoid this bug in future)
+ fix this:

```
path.js:488
      throw new TypeError('Arguments to path.join must be strings');
            ^
TypeError: Arguments to path.join must be strings
    at Object.posix.join (path.js:488:13)
    at relative (/my_package/node_modules/gulp-minify-css/node_modules/clean-css/lib/urls/rewrite.js:43:45)
    at rebase (/my_package/node_modules/gulp-minify-css/node_modules/clean-css/lib/urls/rewrite.js:71:15)
    at /my_package/node_modules/gulp-minify-css/node_modules/clean-css/lib/urls/rewrite.js:88:44
    at byUrl (/my_package/node_modules/gulp-minify-css/node_modules/clean-css/lib/urls/reduce.js:72:5)
    at reduceAll (/my_package/node_modules/gulp-minify-css/node_modules/clean-css/lib/urls/reduce.js:145:10)
    at rewriteUrls (/my_package/node_modules/gulp-minify-css/node_modules/clean-css/lib/urls/rewrite.js:86:10)
    at IncomingMessage.<anonymous> (/my_package/node_modules/gulp-minify-css/node_modules/clean-css/lib/imports/inliner.js:311:24)
    at IncomingMessage.emit (events.js:129:20)
    at _stream_readable.js:908:16
```

**Comment by shinnn** [comment]
> fix version in `package.json` (remove `^` for every dependency to avoid this bug in future)

No thanks. It's all clean-css's fault for breaking things without major version bump. [Changing the dafault option value](https://github.com/jakubpawlowicz/clean-css/issues/654#issuecomment-140053451) requires a version bump to v4.0.0, but the author doesn't.

> fix this:

https://github.com/murphydanger/gulp-minify-css/issues/82#issuecomment-87196977

**Comment by g----** [comment]
I meant that by removing `^` from `package.json` you will prevent any future breakdown caused by external library update.

**Comment by shinnn** [comment]
gulp-minify-css is not to blame for "any future breakdown caused by external library update". The reason why you ran into this problem is clean-css doesn't follow [SemVer specification](http://semver.org/).

Again https://github.com/murphydanger/gulp-minify-css/issues/120#issuecomment-140108062, 

> I don't want to include any workarounds for the problem in this plugin.

**Comment by ethanclevenger91** [comment]
Well it's not a workaround - it's compatibiliy. While I can sympathize with a desire for proper SemVer, even if clean-css went and bumped the version number _now_, the broken one is already out in the wild - they could bump to 4.0.0 right now, but you're `^` would still grab the broken one. I'm not sure they can go back and remove that version from existence and create a new one at 4.0.0. If they _can_, then let's get an issue open on the repo.
